Initialize SIG folder for sig-networking
kubeedge/community pull request #103
Opened 2022-08-23 07:12 UTC by Poorunga

2022-09-14 01:52 UTC, benjaminhuo requested changes

2022-09-14 01:52 UTC, benjaminhuo commented on sig-networking/charter.md
> +    - Edge Physical Network Layer: Physical networks in edge scenarios are generally based on area isolation, and the physical network layer is almost all hardware infrastructure (such as routers, sw
```suggestion
    - Edge Physical Network Layer: Physical networks in edge scenarios are generally based on area isolation, and the physical network layer is almost all hardware infrastructure (such as routers, switches, etc.). It is difficult for us to propose solutions at this layer, so we mainly focus on the upper layers.
```

2022-09-14 01:52 UTC, benjaminhuo commented on sig-networking/charter.md
> +    - Edge Tunnel Network Layer: The core task of this layer is to connect the split physical network at the lower layer, so as to shield the complexity of the physical network topology. The main cap
```suggestion
    - Edge Tunnel Network Layer: The core task of this layer is to connect the split physical network at the lower layer, so as to shield the complexity of the physical network topology. The main capability of the tunnel network layer is to provide tunnel technology, encryption technology, etc. The mainstream industry implementations include libp2p, ipsec, and wireguard, etc.
```

2022-09-14 01:52 UTC, benjaminhuo commented on sig-networking/charter.md
> +    - Edge Virtual Network Layer: K8s provides the concept of service, which can access a service through a virtual IP address (also called cluster IP). This is the core function of the edge virtual
```suggestion
    - Edge Virtual Network Layer: K8s provides the concept of service, which can access a service through a virtual IP address (also called cluster IP). This is the core function of the edge virtual network layer, which is mainly responsible for the transparent proxying and load balancing of the application exposed service. Popular implementations include kube-proxy, and cilium, etc.
```

2022-11-07 09:10 UTC, Poorunga commented on sig-networking/charter.md
> +    - Edge Physical Network Layer: Physical networks in edge scenarios are generally based on area isolation, and the physical network layer is almost all hardware infrastructure (such as routers, sw
done

2022-11-07 09:10 UTC, Poorunga commented on sig-networking/charter.md
> +    - Edge Tunnel Network Layer: The core task of this layer is to connect the split physical network at the lower layer, so as to shield the complexity of the physical network topology. The main cap
done

2022-11-07 09:10 UTC, Poorunga commented on sig-networking/charter.md
> +    - Edge Virtual Network Layer: K8s provides the concept of service, which can access a service through a virtual IP address (also called cluster IP). This is the core function of the edge virtual
done

2022-11-07 09:10 UTC, Poorunga commented on sig-networking/README.md
> +- Fisher Xu (@fisherxu), Huawei
done

2022-11-07 09:15 UTC, benjaminhuo commented
/lgtm

2022-11-10 04:02 UTC, Poorunga commented
The refresh is complete, please review.

/cc  @benjaminhuo @dingyin @fisherxu @huanwei @kevin-wangzefeng

2022-11-10 04:57 UTC, benjaminhuo commented
/lgtm

2022-11-14 02:24 UTC, huanwei commented
/lgtm

2022-12-07 02:07 UTC, dingyin commented
/lgtm

2022-12-07 03:31 UTC, fisherxu reviewed
/lgtm

2022-12-21 11:59 UTC, kevin-wangzefeng commented
/lgtm
/approve

Thanks

2022-12-22 03:34 UTC, merged