WIP add sig node charter
kubeedge/community pull request #89
Opened 2022-07-08 01:28 UTC by Shelley-BaoYue

Signed-off-by: Shelley-BaoYue <baoyue2@huawei.com>

add:
/sig-node

2022-09-14 01:37 UTC, benjaminhuo requested changes

2022-09-14 01:37 UTC, benjaminhuo commented on sig-node/charter.md
> +- Communication across node, such as node dynamic trunk. (with [EdgeMesh](https://github.com/kubeedge/edgemesh))
```suggestion
- Communication across nodes, such as node dynamic trunk. (with [EdgeMesh](https://github.com/kubeedge/edgemesh))
```

2022-10-17 03:45 UTC, Shelley-BaoYue commented on sig-node/charter.md
> +The SIG Node is responsible for the component that support the controlled interactions between pods and host resources. We manager the lifecycle of node and pods scheduled to the node. We focus on en
> 

Done.

2022-10-17 03:46 UTC, Shelley-BaoYue commented on sig-node/charter.md
> +- Communication across node, such as node dynamic trunk. (with [EdgeMesh](https://github.com/kubeedge/edgemesh))
> 

fixed.

2022-10-17 06:25 UTC, benjaminhuo commented
/lgtm

2022-12-07 02:07 UTC, dingyin commented
/lgtm

2022-12-07 03:31 UTC, fisherxu reviewed
/lgtm

2022-12-21 12:38 UTC, kevin-wangzefeng commented
/lgtm

2022-12-22 03:32 UTC, fisherxu commented
/approve

2022-12-22 03:33 UTC, merged